spring:
   profiles:
      active:
        - beta
---

spring:
  profiles: beta
  application:
      name: turbine
  cloud:
    stream:
      kafka:
        binder:
          brokers: 39.99.175.175

turbine:
  appConfig: piclibapi,piclibweb,piclibwap,userapi,userweb,userwap
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")
