spring:
   profiles:
      active:
        - beta
---

spring:
  profiles: beta
  application:
      name: turbine

turbine:
  appConfig: piclibapi,piclibweb,piclibwap,userapi,userweb,userwap
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")
